  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('AbsenceEventCategoryDescriptor',1,1)) + substring('AbsenceEventCategoryDescriptor',2,100), lower(substring('AbsenceEventCategoryDescriptor',1,1)) + substring('AbsenceEventCategoryDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('AbsenceEventCategoryDescriptor',1,1)) + substring('AbsenceEventCategoryDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('ApplicationEventResultDescriptor',1,1)) + substring('ApplicationEventResultDescriptor',2,100), lower(substring('ApplicationEventResultDescriptor',1,1)) + substring('ApplicationEventResultDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('ApplicationEventResultDescriptor',1,1)) + substring('ApplicationEventResultDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('ApplicationEventTypeDescriptor',1,1)) + substring('ApplicationEventTypeDescriptor',2,100), lower(substring('ApplicationEventTypeDescriptor',1,1)) + substring('ApplicationEventTypeDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('ApplicationEventTypeDescriptor',1,1)) + substring('ApplicationEventTypeDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('ApplicationSourceDescriptor',1,1)) + substring('ApplicationSourceDescriptor',2,100), lower(substring('ApplicationSourceDescriptor',1,1)) + substring('ApplicationSourceDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('ApplicationSourceDescriptor',1,1)) + substring('ApplicationSourceDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('ApplicationStatusDescriptor',1,1)) + substring('ApplicationStatusDescriptor',2,100), lower(substring('ApplicationStatusDescriptor',1,1)) + substring('ApplicationStatusDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('ApplicationStatusDescriptor',1,1)) + substring('ApplicationStatusDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('BackgroundCheckStatusDescriptor',1,1)) + substring('BackgroundCheckStatusDescriptor',2,100), lower(substring('BackgroundCheckStatusDescriptor',1,1)) + substring('BackgroundCheckStatusDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('BackgroundCheckStatusDescriptor',1,1)) + substring('BackgroundCheckStatusDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('BackgroundCheckTypeDescriptor',1,1)) + substring('BackgroundCheckTypeDescriptor',2,100), lower(substring('BackgroundCheckTypeDescriptor',1,1)) + substring('BackgroundCheckTypeDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('BackgroundCheckTypeDescriptor',1,1)) + substring('BackgroundCheckTypeDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('EmploymentEventTypeDescriptor',1,1)) + substring('EmploymentEventTypeDescriptor',2,100), lower(substring('EmploymentEventTypeDescriptor',1,1)) + substring('EmploymentEventTypeDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('EmploymentEventTypeDescriptor',1,1)) + substring('EmploymentEventTypeDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('EmploymentSeparationReasonDescriptor',1,1)) + substring('EmploymentSeparationReasonDescriptor',2,100), lower(substring('EmploymentSeparationReasonDescriptor',1,1)) + substring('EmploymentSeparationReasonDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('EmploymentSeparationReasonDescriptor',1,1)) + substring('EmploymentSeparationReasonDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('EmploymentSeparationTypeDescriptor',1,1)) + substring('EmploymentSeparationTypeDescriptor',2,100), lower(substring('EmploymentSeparationTypeDescriptor',1,1)) + substring('EmploymentSeparationTypeDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('EmploymentSeparationTypeDescriptor',1,1)) + substring('EmploymentSeparationTypeDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('FundingSourceDescriptor',1,1)) + substring('FundingSourceDescriptor',2,100), lower(substring('FundingSourceDescriptor',1,1)) + substring('FundingSourceDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('FundingSourceDescriptor',1,1)) + substring('FundingSourceDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('HireStatusDescriptor',1,1)) + substring('HireStatusDescriptor',2,100), lower(substring('HireStatusDescriptor',1,1)) + substring('HireStatusDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('HireStatusDescriptor',1,1)) + substring('HireStatusDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('HiringSourceDescriptor',1,1)) + substring('HiringSourceDescriptor',2,100), lower(substring('HiringSourceDescriptor',1,1)) + substring('HiringSourceDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('HiringSourceDescriptor',1,1)) + substring('HiringSourceDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('LevelOfDegreeAwardedDescriptor',1,1)) + substring('LevelOfDegreeAwardedDescriptor',2,100), lower(substring('LevelOfDegreeAwardedDescriptor',1,1)) + substring('LevelOfDegreeAwardedDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('LevelOfDegreeAwardedDescriptor',1,1)) + substring('LevelOfDegreeAwardedDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('OpenStaffPositionEventStatusDescriptor',1,1)) + substring('OpenStaffPositionEventStatusDescriptor',2,100), lower(substring('OpenStaffPositionEventStatusDescriptor',1,1)) + substring('OpenStaffPositionEventStatusDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('OpenStaffPositionEventStatusDescriptor',1,1)) + substring('OpenStaffPositionEventStatusDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('OpenStaffPositionEventTypeDescriptor',1,1)) + substring('OpenStaffPositionEventTypeDescriptor',2,100), lower(substring('OpenStaffPositionEventTypeDescriptor',1,1)) + substring('OpenStaffPositionEventTypeDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('OpenStaffPositionEventTypeDescriptor',1,1)) + substring('OpenStaffPositionEventTypeDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('OpenStaffPositionReasonDescriptor',1,1)) + substring('OpenStaffPositionReasonDescriptor',2,100), lower(substring('OpenStaffPositionReasonDescriptor',1,1)) + substring('OpenStaffPositionReasonDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('OpenStaffPositionReasonDescriptor',1,1)) + substring('OpenStaffPositionReasonDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('StaffEvaluationPeriodDescriptor',1,1)) + substring('StaffEvaluationPeriodDescriptor',2,100), lower(substring('StaffEvaluationPeriodDescriptor',1,1)) + substring('StaffEvaluationPeriodDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('StaffEvaluationPeriodDescriptor',1,1)) + substring('StaffEvaluationPeriodDescriptor',2,100),8,1)

  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('StaffEvaluationRatingLevelDescriptor',1,1)) + substring('StaffEvaluationRatingLevelDescriptor',2,100), lower(substring('StaffEvaluationRatingLevelDescriptor',1,1)) + substring('StaffEvaluationRatingLevelDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('StaffEvaluationRatingLevelDescriptor',1,1)) + substring('StaffEvaluationRatingLevelDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('StaffEvaluationTypeDescriptor',1,1)) + substring('StaffEvaluationTypeDescriptor',2,100), lower(substring('StaffEvaluationTypeDescriptor',1,1)) + substring('StaffEvaluationTypeDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('StaffEvaluationTypeDescriptor',1,1)) + substring('StaffEvaluationTypeDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('SurveyCategoryDescriptor',1,1)) + substring('SurveyCategoryDescriptor',2,100), lower(substring('SurveyCategoryDescriptor',1,1)) + substring('SurveyCategoryDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('SurveyCategoryDescriptor',1,1)) + substring('SurveyCategoryDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('TeacherPreparationProgramTypeDescriptor',1,1)) + substring('TeacherPreparationProgramTypeDescriptor',2,100), lower(substring('TeacherPreparationProgramTypeDescriptor',1,1)) + substring('TeacherPreparationProgramTypeDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('TeacherPreparationProgramTypeDescriptor',1,1)) + substring('TeacherPreparationProgramTypeDescriptor',2,100),8,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('WithdrawReasonDescriptor',1,1)) + substring('WithdrawReasonDescriptor',2,100), lower(substring('WithdrawReasonDescriptor',1,1)) + substring('WithdrawReasonDescriptor',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('WithdrawReasonDescriptor',1,1)) + substring('WithdrawReasonDescriptor',2,100),8,1)