
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('AbsenceEventCategoryType',1,1)) + substring('AbsenceEventCategoryType',2,100), lower(substring('AbsenceEventCategoryType',1,1)) + substring('AbsenceEventCategoryType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('AbsenceEventCategoryType',1,1)) + substring('AbsenceEventCategoryType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('ApplicationEventResultType',1,1)) + substring('ApplicationEventResultType',2,100), lower(substring('ApplicationEventResultType',1,1)) + substring('ApplicationEventResultType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('ApplicationEventResultType',1,1)) + substring('ApplicationEventResultType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('ApplicationEventType',1,1)) + substring('ApplicationEventType',2,100), lower(substring('ApplicationEventType',1,1)) + substring('ApplicationEventType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('ApplicationEventType',1,1)) + substring('ApplicationEventType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('ApplicationSourceType',1,1)) + substring('ApplicationSourceType',2,100), lower(substring('ApplicationSourceType',1,1)) + substring('ApplicationSourceType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('ApplicationSourceType',1,1)) + substring('ApplicationSourceType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('ApplicationStatusType',1,1)) + substring('ApplicationStatusType',2,100), lower(substring('ApplicationStatusType',1,1)) + substring('ApplicationStatusType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('ApplicationStatusType',1,1)) + substring('ApplicationStatusType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('BackgroundCheckType',1,1)) + substring('BackgroundCheckType',2,100), lower(substring('BackgroundCheckType',1,1)) + substring('BackgroundCheckType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('BackgroundCheckType',1,1)) + substring('BackgroundCheckType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('BackgroundCheckStatusType',1,1)) + substring('BackgroundCheckStatusType',2,100), lower(substring('BackgroundCheckStatusType',1,1)) + substring('BackgroundCheckStatusType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('BackgroundCheckStatusType',1,1)) + substring('BackgroundCheckStatusType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('EmploymentEventType',1,1)) + substring('EmploymentEventType',2,100), lower(substring('EmploymentEventType',1,1)) + substring('EmploymentEventType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('EmploymentEventType',1,1)) + substring('EmploymentEventType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('EmploymentSeparationReasonType',1,1)) + substring('EmploymentSeparationReasonType',2,100), lower(substring('EmploymentSeparationReasonType',1,1)) + substring('EmploymentSeparationReasonType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('EmploymentSeparationReasonType',1,1)) + substring('EmploymentSeparationReasonType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('EmploymentSeparationType',1,1)) + substring('EmploymentSeparationType',2,100), lower(substring('EmploymentSeparationType',1,1)) + substring('EmploymentSeparationType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('EmploymentSeparationType',1,1)) + substring('EmploymentSeparationType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('FundingSourceType',1,1)) + substring('FundingSourceType',2,100), lower(substring('FundingSourceType',1,1)) + substring('FundingSourceType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('FundingSourceType',1,1)) + substring('FundingSourceType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('HireStatusType',1,1)) + substring('HireStatusType',2,100), lower(substring('HireStatusType',1,1)) + substring('HireStatusType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('HireStatusType',1,1)) + substring('HireStatusType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('HiringSourceType',1,1)) + substring('HiringSourceType',2,100), lower(substring('HiringSourceType',1,1)) + substring('HiringSourceType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('HiringSourceType',1,1)) + substring('HiringSourceType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('InternalExternalHireType',1,1)) + substring('InternalExternalHireType',2,100), lower(substring('InternalExternalHireType',1,1)) + substring('InternalExternalHireType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('InternalExternalHireType',1,1)) + substring('InternalExternalHireType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('LevelOfDegreeAwardedType',1,1)) + substring('LevelOfDegreeAwardedType',2,100), lower(substring('LevelOfDegreeAwardedType',1,1)) + substring('LevelOfDegreeAwardedType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('LevelOfDegreeAwardedType',1,1)) + substring('LevelOfDegreeAwardedType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('OpenStaffPositionEventStatusType',1,1)) + substring('OpenStaffPositionEventStatusType',2,100), lower(substring('OpenStaffPositionEventStatusType',1,1)) + substring('OpenStaffPositionEventStatusType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('OpenStaffPositionEventStatusType',1,1)) + substring('OpenStaffPositionEventStatusType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('OpenStaffPositionEventType',1,1)) + substring('OpenStaffPositionEventType',2,100), lower(substring('OpenStaffPositionEventType',1,1)) + substring('OpenStaffPositionEventType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('OpenStaffPositionEventType',1,1)) + substring('OpenStaffPositionEventType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('OpenStaffPositionReasonType',1,1)) + substring('OpenStaffPositionReasonType',2,100), lower(substring('OpenStaffPositionReasonType',1,1)) + substring('OpenStaffPositionReasonType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('OpenStaffPositionReasonType',1,1)) + substring('OpenStaffPositionReasonType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('QuestionFormType',1,1)) + substring('QuestionFormType',2,100), lower(substring('QuestionFormType',1,1)) + substring('QuestionFormType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('QuestionFormType',1,1)) + substring('QuestionFormType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('SurveyCategoryType',1,1)) + substring('SurveyCategoryType',2,100), lower(substring('SurveyCategoryType',1,1)) + substring('SurveyCategoryType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('SurveyCategoryType',1,1)) + substring('SurveyCategoryType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('StaffEvaluationPeriodType',1,1)) + substring('StaffEvaluationPeriodType',2,100), lower(substring('StaffEvaluationPeriodType',1,1)) + substring('StaffEvaluationPeriodType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('StaffEvaluationPeriodType',1,1)) + substring('StaffEvaluationPeriodType',2,100),7,1)

  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('StaffEvaluationRatingLevelType',1,1)) + substring('StaffEvaluationRatingLevelType',2,100), lower(substring('StaffEvaluationRatingLevelType',1,1)) + substring('StaffEvaluationRatingLevelType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('StaffEvaluationRatingLevelType',1,1)) + substring('StaffEvaluationRatingLevelType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('StaffEvaluationType',1,1)) + substring('StaffEvaluationType',2,100), lower(substring('StaffEvaluationType',1,1)) + substring('StaffEvaluationType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('StaffEvaluationType',1,1)) + substring('StaffEvaluationType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('TeacherPreparationProgramType',1,1)) + substring('TeacherPreparationProgramType',2,100), lower(substring('TeacherPreparationProgramType',1,1)) + substring('TeacherPreparationProgramType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('TeacherPreparationProgramType',1,1)) + substring('TeacherPreparationProgramType',2,100),7,1)
  
  insert into [EdFi_Security].[dbo].[ResourceClaims] (DisplayName,ResourceName, ClaimName, ParentResourceClaimId,Application_ApplicationId) values (lower(substring('WithdrawReasonType',1,1)) + substring('WithdrawReasonType',2,100), lower(substring('WithdrawReasonType',1,1)) + substring('WithdrawReasonType',2,100),'http://ed-fi.org/ods/identity/claims/' + lower(substring('WithdrawReasonType',1,1)) + substring('WithdrawReasonType',2,100),7,1)